// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_path_ from "./routes/api/[...path].ts";
import * as $index from "./routes/index.tsx";
import * as $Chat from "./islands/Chat.tsx";
import * as $RegisterAuthenticatorButton from "./islands/RegisterAuthenticatorButton.tsx";
import * as $SignInButton from "./islands/SignInButton.tsx";
import * as $SignOutButton from "./islands/SignOutButton.tsx";
import * as $SignUpButton from "./islands/SignUpButton.tsx";
import * as $UserInfo from "./islands/UserInfo.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/[...path].ts": $api_path_,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/Chat.tsx": $Chat,
    "./islands/RegisterAuthenticatorButton.tsx": $RegisterAuthenticatorButton,
    "./islands/SignInButton.tsx": $SignInButton,
    "./islands/SignOutButton.tsx": $SignOutButton,
    "./islands/SignUpButton.tsx": $SignUpButton,
    "./islands/UserInfo.tsx": $UserInfo,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
