name: Deploy

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write # This is required to allow the GitHub Action to authenticate with Deno Deploy.
      contents: read

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Set up Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Check
        run: deno task check

      - name: Build
        run: deno task build
        env:
          FIREBASE_PROJECT_ID: "__dummy_project_id__"
          FIREBASE_CLIENT_EMAIL: "__dummy_client_email__"
          FIREBASE_PRIVATE_KEY: "__dummy_private_key__"

      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: pass-key-memo # the name of the project on Deno Deploy
          entrypoint: main.ts # the entrypoint to deploy
